name: Comby CI
on:
  push:
    branches:
      - tls
      - master
  pull_request:
    types: [opened, repoened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install pcre
        run: sudo apt-get install -y libpcre3-dev libev4 libev-dev

      - name: install Comby
        run: TERM=xterm bash <(curl -sL get.comby.dev)

      - name: run tests
        run: test/run.sh
